name: matrixWFtest

on:
  push:

jobs:
  jobmat:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        variable1: [value1, value2]
        anothervariable: [ av1, av2]
        include:
          - variable1: value3
          - variable1: value4
            anothervariable: av3
        exclude:
          - variable1: value1
    steps:
      - run: echo ${{ matrix.variable1 }}
